"""Fakes for the hands tests: Win32 windows, input, clipboard, screen.
Nothing here touches the real desktop."""

from __future__ import annotations

from dataclasses import replace
from typing import Any

from sam.hands.windows import WindowInfo, Windows

OWN_PID = 999_999

# A subset of this PC's real Start-menu index (shell:AppsFolder, 2026-09-24).
START_ROWS: list[dict[str, Any]] = [
    {"app_id": "Chrome", "name": "Google Chrome", "target": r"C:\Program Files\Google\Chrome\Application\chrome.exe"},
    {"app_id": "MSEdge", "name": "Microsoft Edge",
     "target": r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe"},
    {"app_id": "TradingView.Desktop_n534cwy3pjxzj!TradingView.Desktop", "name": "TradingView", "target": None},
    {"app_id": "31178TradingViewInc.TradingView_q4jpyh43s5mv6!TradingView.Desktop", "name": "TradingView",
     "target": None},
    {"app_id": r"C:\Users\samit\AppData\Roaming\Telegram Desktop\unins000.exe", "name": "Uninstall Telegram",
     "target": r"C:\Users\samit\AppData\Roaming\Telegram Desktop\unins000.exe"},
    {"app_id": "Telegram.TelegramDesktop", "name": "Telegram",
     "target": r"C:\Users\samit\AppData\Roaming\Telegram Desktop\Telegram.exe"},
    {"app_id": r"{6D809377-6AF0-444B-8957-A3773F02200E}\MetaTrader 5\terminal64.exe", "name": "MetaTrader 5",
     "target": r"C:\Program Files\MetaTrader 5\terminal64.exe"},
    {"app_id": "5319275A.WhatsAppDesktop_cv1g1gvanyjgm!App", "name": "WhatsApp", "target": None},
    {"app_id": "Microsoft.Office.EXCEL.EXE.15", "name": "Excel",
     "target": r"C:\Program Files\Microsoft Office\root\Office16\EXCEL.EXE"},
    {"app_id": "Microsoft.Office.WINWORD.EXE.15", "name": "Word",
     "target": r"C:\Program Files\Microsoft Office\root\Office16\WINWORD.EXE"},
    {"app_id": "Microsoft.VisualStudioCode", "name": "Visual Studio Code",
     "target": r"C:\Users\samit\AppData\Local\Programs\Microsoft VS Code\Code.exe"},
    {"app_id": "Anysphere.Cursor", "name": "Cursor", "target": r"C:\Users\samit\AppData\Local\Programs\cursor\Cursor.exe"},
    {"app_id": "Microsoft.WindowsNotepad_8wekyb3d8bbwe!App", "name": "Notepad", "target": None},
    {"app_id": "Microsoft.WindowsCalculator_8wekyb3d8bbwe!App", "name": "Calculator", "target": None},
    {"app_id": "windows.immersivecontrolpanel_cw5n1h2txyewy!microsoft.windows.immersivecontrolpanel",
     "name": "Settings", "target": None},
    {"app_id": "Microsoft.Windows.Explorer", "name": "File Explorer", "target": "::{52205FD8-5DFB-447D-801A-D0B52F2E83E1}"},
    {"app_id": "Microsoft.AutoGenerated.{923DD477-5846-686B-A659-0FCCD73851A8}", "name": "Task Manager",
     "target": r"C:\Windows\system32\taskmgr.exe", "target_args": "/7"},
    {"app_id": "Microsoft.Paint_8wekyb3d8bbwe!App", "name": "Paint", "target": None},
    {"app_id": "Microsoft.WindowsTerminal_8wekyb3d8bbwe!App", "name": "Terminal", "target": None},
    {"app_id": "Microsoft.ScreenSketch_8wekyb3d8bbwe!App", "name": "Snipping Tool", "target": None},
    {"app_id": "Microsoft.Windows.ControlPanel", "name": "Control Panel", "target": None},
    {"app_id": "Microsoft.Office.POWERPNT.EXE.15", "name": "PowerPoint",
     "target": r"C:\Program Files\Microsoft Office\root\Office16\POWERPNT.EXE"},
    {"app_id": r"C:\Users\samit\Desktop\Tor Browser\Browser\firefox.exe", "name": "Tor Browser",
     "target": r"C:\Users\samit\Desktop\Tor Browser\Browser\firefox.exe"},
    {"app_id": "OBSProject.OBSStudio", "name": "OBS Studio", "target": r"C:\Program Files\obs-studio\bin\64bit\obs64.exe"},
]


def win(hwnd: int, title: str, process: str, *, pid: int = 100, rect: tuple[int, int, int, int] = (100, 100, 900, 700),
        minimized: bool = False, maximized: bool = False, cls: str = "Window") -> WindowInfo:
    return WindowInfo(hwnd=hwnd, title=title, process=process, pid=pid, rect=rect, minimized=minimized, visible=True,
                      maximized=maximized, cls=cls)


class FakeWinApi:
    """In-memory window manager with Win32-like semantics."""

    def __init__(self, windows: list[WindowInfo], *, foreground: int | None = None) -> None:
        self.state: dict[int, dict[str, Any]] = {
            w.hwnd: {"info": w, "min": w.minimized, "max": w.maximized, "alive": True, "rect": w.rect}
            for w in windows}
        self.fg = foreground
        self.calls: list[tuple[Any, ...]] = []
        self.close_behavior: dict[int, str] = {}
        self.refuse_focus: set[int] = set()
        self.work = (0, 0, 2880, 1728)
        self.border = (11, 0, 11, 11)
        self.min_width: dict[int, int] = {}

    def add(self, window: WindowInfo) -> None:
        self.state[window.hwnd] = {"info": window, "min": window.minimized, "max": window.maximized, "alive": True,
                                   "rect": window.rect}

    def enum(self, include_hidden: bool = False) -> list[WindowInfo]:
        return [replace(s["info"], minimized=s["min"], maximized=s["max"], rect=s["rect"], foreground=h == self.fg)
                for h, s in self.state.items() if s["alive"]]

    def foreground(self) -> int:
        return self.fg or 0

    def is_window(self, hwnd: int) -> bool:
        return bool(self.state.get(hwnd, {}).get("alive"))

    def is_iconic(self, hwnd: int) -> bool:
        return bool(self.state[hwnd]["min"])

    def is_zoomed(self, hwnd: int) -> bool:
        return bool(self.state[hwnd]["max"])

    def show(self, hwnd: int, command: int) -> None:
        self.calls.append(("show", hwnd, command))
        state = self.state[hwnd]
        if command == 6:
            state["min"] = True
            if self.fg == hwnd:
                self.fg = None
        elif command == 3:
            state["max"], state["min"] = True, False
        elif command == 9:
            state["min"] = False
            if not state["min"]:
                state["max"] = False

    def set_foreground(self, hwnd: int) -> bool:
        self.calls.append(("foreground", hwnd))
        if hwnd in self.refuse_focus:
            return False
        self.fg = hwnd
        return True

    def post_close(self, hwnd: int) -> None:
        self.calls.append(("close", hwnd))
        if self.close_behavior.get(hwnd, "close") == "close":
            self.state[hwnd]["alive"] = False

    def owned_popups(self, hwnd: int) -> list[str]:
        return ["Notepad"] if self.close_behavior.get(hwnd) == "prompt" else []

    def work_area(self, hwnd: int) -> tuple[int, int, int, int]:
        return self.work

    def rect(self, hwnd: int) -> tuple[int, int, int, int]:
        return self.state[hwnd]["rect"]

    def frame_rect(self, hwnd: int) -> tuple[int, int, int, int]:
        r, b = self.state[hwnd]["rect"], self.border
        return (r[0] + b[0], r[1] + b[1], r[2] - b[2], r[3] - b[3])

    def move(self, hwnd: int, rect: tuple[int, int, int, int]) -> None:
        self.calls.append(("move", hwnd, rect))
        minimum = self.min_width.get(hwnd)
        if minimum and rect[2] - rect[0] < minimum:
            rect = (rect[0], rect[1], rect[0] + minimum, rect[3])
        self.state[hwnd]["rect"] = rect


def fake_windows(windows: list[WindowInfo], *, foreground: int | None = None) -> tuple[Windows, FakeWinApi]:
    api = FakeWinApi(windows, foreground=foreground)
    return Windows(api, own_pid=OWN_PID, settle_s=0.05), api


class RecorderBackend:
    """Input backend that records events instead of sending them."""

    def __init__(self) -> None:
        self.events: list[tuple[Any, ...]] = []
        self.pos = (0, 0)

    def key(self, vk: int, up: bool) -> None:
        self.events.append(("key", vk, "up" if up else "down"))

    def unicode(self, unit: int, up: bool) -> None:
        self.events.append(("uni", unit, "up" if up else "down"))

    def move(self, x: int, y: int) -> None:
        self.pos = (x, y)
        self.events.append(("move", x, y))

    def button(self, button: str, up: bool) -> None:
        self.events.append(("button", button, "up" if up else "down"))

    def wheel(self, delta: int) -> None:
        self.events.append(("wheel", delta))

    def cursor(self) -> tuple[int, int]:
        return self.pos


class FakeClipboard:
    """Clipboard with formats; records the order of operations."""

    def __init__(self, formats: list[tuple[int, bytes]] | None = None, *, locked: bool = False) -> None:
        self.formats = list(formats or [])
        self.locked = locked
        self.log: list[str] = []
        self.private: list[bool] = []

    def snapshot(self) -> list[tuple[int, bytes]]:
        if self.locked:
            raise OSError("the clipboard is locked by another app")
        self.log.append("snapshot")
        return list(self.formats)

    def set_text(self, text: str, *, private: bool = True) -> None:
        self.log.append(f"set:{text}")
        self.private.append(private)
        self.formats = [(13, (text + "\x00").encode("utf-16-le"))]

    def restore(self, saved: list[tuple[int, bytes]]) -> None:
        self.log.append("restore")
        self.formats = list(saved)

    def get_text(self) -> str | None:
        for fmt, data in self.formats:
            if fmt == 13:
                return data.decode("utf-16-le").split("\x00", 1)[0]
        return None


class FakeShot:
    def __init__(self, left: int, top: int, width: int, height: int, out_width: int, out_height: int) -> None:
        self.left, self.top, self.width, self.height = left, top, width, height
        self.out_width, self.out_height = out_width, out_height
        self.data = b"\xff\xd8fake"
        self.mime = "image/jpeg"
        self.fmt = "jpeg"
        self.blanked: list[Any] = []


__all__ = ["FakeClipboard", "FakeShot", "FakeWinApi", "OWN_PID", "RecorderBackend", "START_ROWS", "fake_windows", "win"]
