"""SQLite store (``<data_dir>/sam2.sqlite3``): WAL, namespaced migrations.

One connection shared by the core loop and the UI thread, guarded by an RLock
(``check_same_thread=False``). Every query SAM makes is small (single-row
inserts, indexed reads) so calling these sync methods directly from the
asyncio loop is fine; for anything heavy use ``await db.run(fn)``.

All timestamps are REAL unix epoch seconds (UTC). JSON columns hold UTF-8
JSON text (``ensure_ascii=False``).

Packages that need their own tables do NOT edit this file: they call
``app.db.ensure_schema("<namespace>", [(1, "CREATE TABLE ..."), ...])`` in
their ``register(app)``. Versions are tracked per namespace in
``schema_versions``.
"""

from __future__ import annotations

import asyncio
import datetime as _dt
import json
import sqlite3
import threading
import time
from contextlib import contextmanager
from pathlib import Path
from typing import Any, Callable, Iterable, Iterator, Sequence

from .textnorm import normalize_ckb

Migration = tuple[int, "str | Callable[[sqlite3.Connection], None]"]

# --- core schema (namespace "core") ---------------------------------------------
# Owners (who writes rows): settings=config; facts/notes/conversations/turns=
# brain.memory+conversation; strategy_*=trading engine; alerts=trading monitor;
# drawings=trading chart bridge; v1_archive=migrate_v1; usage_counters=llm+voice;
# timings=timing; activity=tools registry + anyone via log_activity().
_CORE_V1 = """
CREATE TABLE IF NOT EXISTS settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,                 -- JSON
    updated_at REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS facts (
    id INTEGER PRIMARY KEY,
    text TEXT NOT NULL,                  -- as said/typed (Sorani or English)
    text_norm TEXT NOT NULL,             -- normalize_ckb(text): dedup + FTS
    kind TEXT NOT NULL DEFAULT 'fact',   -- fact|preference|person|project|trading
    tags TEXT NOT NULL DEFAULT '',       -- space separated
    source TEXT NOT NULL DEFAULT 'user', -- user|extracted|import
    confidence REAL NOT NULL DEFAULT 1.0,
    created_at REAL NOT NULL,
    updated_at REAL NOT NULL,
    last_used_at REAL,
    use_count INTEGER NOT NULL DEFAULT 0,
    deleted INTEGER NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX IF NOT EXISTS facts_norm_unique ON facts(text_norm) WHERE deleted = 0;
CREATE VIRTUAL TABLE IF NOT EXISTS facts_fts USING fts5(
    text_norm, tags, content='facts', content_rowid='id', tokenize='trigram');
CREATE TRIGGER IF NOT EXISTS facts_ai AFTER INSERT ON facts BEGIN
    INSERT INTO facts_fts(rowid, text_norm, tags) VALUES (new.id, new.text_norm, new.tags);
END;
CREATE TRIGGER IF NOT EXISTS facts_ad AFTER DELETE ON facts BEGIN
    INSERT INTO facts_fts(facts_fts, rowid, text_norm, tags) VALUES ('delete', old.id, old.text_norm, old.tags);
END;
CREATE TRIGGER IF NOT EXISTS facts_au AFTER UPDATE ON facts BEGIN
    INSERT INTO facts_fts(facts_fts, rowid, text_norm, tags) VALUES ('delete', old.id, old.text_norm, old.tags);
    INSERT INTO facts_fts(rowid, text_norm, tags) VALUES (new.id, new.text_norm, new.tags);
END;

CREATE TABLE IF NOT EXISTS conversations (
    id INTEGER PRIMARY KEY,
    started_at REAL NOT NULL,
    ended_at REAL,
    source TEXT NOT NULL DEFAULT 'voice', -- voice|text|mixed
    title TEXT NOT NULL DEFAULT '',
    summary TEXT NOT NULL DEFAULT '',
    facts_extracted INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS turns (
    id INTEGER PRIMARY KEY,
    conversation_id INTEGER NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    at REAL NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('user','assistant','system','tool')),
    text TEXT NOT NULL,
    source TEXT NOT NULL DEFAULT 'voice', -- live|cascade|text|worker|system
    meta TEXT                             -- JSON (tool name, timings, ...)
);
CREATE INDEX IF NOT EXISTS turns_conversation ON turns(conversation_id, id);

CREATE TABLE IF NOT EXISTS notes (
    id INTEGER PRIMARY KEY,
    title TEXT NOT NULL DEFAULT '',
    body TEXT NOT NULL,
    body_norm TEXT NOT NULL,
    kind TEXT NOT NULL DEFAULT 'note',    -- note|theory|journal|doc
    tags TEXT NOT NULL DEFAULT '',
    source TEXT NOT NULL DEFAULT 'user',
    created_at REAL NOT NULL,
    updated_at REAL NOT NULL
);
CREATE VIRTUAL TABLE IF NOT EXISTS notes_fts USING fts5(
    title, body_norm, tags, content='notes', content_rowid='id', tokenize='trigram');
CREATE TRIGGER IF NOT EXISTS notes_ai AFTER INSERT ON notes BEGIN
    INSERT INTO notes_fts(rowid, title, body_norm, tags) VALUES (new.id, new.title, new.body_norm, new.tags);
END;
CREATE TRIGGER IF NOT EXISTS notes_ad AFTER DELETE ON notes BEGIN
    INSERT INTO notes_fts(notes_fts, rowid, title, body_norm, tags) VALUES ('delete', old.id, old.title, old.body_norm, old.tags);
END;
CREATE TRIGGER IF NOT EXISTS notes_au AFTER UPDATE ON notes BEGIN
    INSERT INTO notes_fts(notes_fts, rowid, title, body_norm, tags) VALUES ('delete', old.id, old.title, old.body_norm, old.tags);
    INSERT INTO notes_fts(rowid, title, body_norm, tags) VALUES (new.id, new.title, new.body_norm, new.tags);
END;

CREATE TABLE IF NOT EXISTS strategy_cards (
    id TEXT PRIMARY KEY,                  -- short slug, e.g. 'asia-sweep-fvg'
    title_ckb TEXT NOT NULL,
    title_en TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','active','archived')),
    version INTEGER NOT NULL DEFAULT 1,
    card TEXT NOT NULL,                   -- full card JSON of the current version
    summary_ckb TEXT NOT NULL DEFAULT '', -- one line for the prompt index
    source_text TEXT NOT NULL DEFAULT '', -- verbatim as the user gave it
    search_text TEXT NOT NULL DEFAULT '', -- normalize_ckb(titles + summary + rules) for FTS
    note TEXT NOT NULL DEFAULT '',
    created_at REAL NOT NULL,
    updated_at REAL NOT NULL
);
CREATE TABLE IF NOT EXISTS strategy_card_versions (
    card_id TEXT NOT NULL REFERENCES strategy_cards(id) ON DELETE CASCADE,
    version INTEGER NOT NULL,
    card TEXT NOT NULL,
    reason TEXT NOT NULL DEFAULT '',
    created_at REAL NOT NULL,
    PRIMARY KEY (card_id, version)
);
CREATE VIRTUAL TABLE IF NOT EXISTS strategy_fts USING fts5(
    search_text, content='strategy_cards', content_rowid='rowid', tokenize='trigram');
CREATE TRIGGER IF NOT EXISTS strategy_ai AFTER INSERT ON strategy_cards BEGIN
    INSERT INTO strategy_fts(rowid, search_text) VALUES (new.rowid, new.search_text);
END;
CREATE TRIGGER IF NOT EXISTS strategy_ad AFTER DELETE ON strategy_cards BEGIN
    INSERT INTO strategy_fts(strategy_fts, rowid, search_text) VALUES ('delete', old.rowid, old.search_text);
END;
CREATE TRIGGER IF NOT EXISTS strategy_au AFTER UPDATE ON strategy_cards BEGIN
    INSERT INTO strategy_fts(strategy_fts, rowid, search_text) VALUES ('delete', old.rowid, old.search_text);
    INSERT INTO strategy_fts(rowid, search_text) VALUES (new.rowid, new.search_text);
END;

CREATE TABLE IF NOT EXISTS alerts (
    id INTEGER PRIMARY KEY,
    kind TEXT NOT NULL,                   -- price_cross|zone_touch|candle_close|volume_spike|strategy_state
    symbol TEXT NOT NULL,
    timeframe TEXT,
    params TEXT NOT NULL,                 -- JSON spec (level, direction, low/high, k, n, ...)
    note TEXT NOT NULL DEFAULT '',
    strategy_id TEXT,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','fired','cancelled','expired')),
    repeat INTEGER NOT NULL DEFAULT 0,
    created_at REAL NOT NULL,
    expires_at REAL,
    fired_at REAL,
    fire_count INTEGER NOT NULL DEFAULT 0,
    last_value REAL,
    last_text_ckb TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS alerts_status ON alerts(status);

CREATE TABLE IF NOT EXISTS drawings (
    id INTEGER PRIMARY KEY,
    tv_id TEXT NOT NULL,                  -- TradingView entity id (SAM-owned only)
    kind TEXT NOT NULL,
    symbol TEXT NOT NULL DEFAULT '',
    timeframe TEXT NOT NULL DEFAULT '',
    points TEXT NOT NULL,                 -- JSON [{"time": unix_s, "price": float}]
    text TEXT NOT NULL DEFAULT '',
    tag TEXT NOT NULL DEFAULT '',         -- e.g. 'analysis:<id>', 'levels', 'user-request'
    created_at REAL NOT NULL,
    removed_at REAL
);
CREATE INDEX IF NOT EXISTS drawings_live ON drawings(removed_at, symbol);

CREATE TABLE IF NOT EXISTS v1_archive (
    id INTEGER PRIMARY KEY,
    source_table TEXT NOT NULL,
    source_id TEXT NOT NULL,
    payload TEXT NOT NULL,                -- JSON row as read from v1
    note TEXT NOT NULL DEFAULT '',
    imported_at REAL NOT NULL,
    UNIQUE (source_table, source_id)
);

CREATE TABLE IF NOT EXISTS usage_counters (
    day TEXT NOT NULL,                    -- YYYY-MM-DD in the provider's quota zone
    provider TEXT NOT NULL,               -- gemini|groq|omniroute|openrouter|kurdishtts
    model TEXT NOT NULL,
    kind TEXT NOT NULL DEFAULT 'text',    -- text|vision|live|tts|stt|computer_use
    requests INTEGER NOT NULL DEFAULT 0,
    errors INTEGER NOT NULL DEFAULT 0,
    rate_limited INTEGER NOT NULL DEFAULT 0,
    tokens_in INTEGER NOT NULL DEFAULT 0,
    tokens_out INTEGER NOT NULL DEFAULT 0,
    units REAL NOT NULL DEFAULT 0,        -- chars (TTS) / seconds (STT, Live)
    PRIMARY KEY (day, provider, model, kind)
);

CREATE TABLE IF NOT EXISTS timings (
    id INTEGER PRIMARY KEY,
    at REAL NOT NULL,
    turn_id TEXT,
    kind TEXT NOT NULL DEFAULT '',        -- live|cascade|text|tool|worker|analysis|startup
    stage TEXT NOT NULL,
    ms REAL NOT NULL,
    extra TEXT                            -- JSON
);
CREATE INDEX IF NOT EXISTS timings_turn ON timings(turn_id);
CREATE INDEX IF NOT EXISTS timings_at ON timings(at);

CREATE TABLE IF NOT EXISTS activity (
    id INTEGER PRIMARY KEY,
    at REAL NOT NULL,
    kind TEXT NOT NULL,                   -- tool|confirm|alert|worker|error|system|voice
    name TEXT NOT NULL DEFAULT '',
    ok INTEGER,
    summary TEXT NOT NULL DEFAULT '',     -- redacted
    detail TEXT,                          -- redacted JSON
    duration_ms REAL,
    source TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS activity_at ON activity(at);
"""

CORE_MIGRATIONS: list[Migration] = [(1, _CORE_V1)]


def _json(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, default=str)


def fts_match_expr(text: str, *, max_terms: int = 12) -> str | None:
    """Build a safe FTS5 MATCH expression for a trigram index.

    Trigram tokens need >= 3 characters, so shorter words are dropped; each
    term is double-quoted (no FTS syntax injection) and OR-ed. Returns None
    when nothing searchable remains (callers then fall back to LIKE).
    """
    terms: list[str] = []
    for word in normalize_ckb(text, strip_punct=True).split():
        if len(word) >= 3 and word not in terms:
            terms.append(word.replace('"', '""'))
        if len(terms) >= max_terms:
            break
    if not terms:
        return None
    return " OR ".join(f'"{t}"' for t in terms)


class Database:
    """Thread-safe SQLite wrapper. See module docstring for conventions."""

    def __init__(self, path: Path | str) -> None:
        self.path = str(path)
        if self.path != ":memory:":
            Path(self.path).parent.mkdir(parents=True, exist_ok=True)
        self._lock = threading.RLock()
        self._conn = sqlite3.connect(self.path, check_same_thread=False, isolation_level=None, timeout=10)
        self._conn.row_factory = sqlite3.Row
        with self._lock:
            if self.path != ":memory:":
                self._conn.execute("PRAGMA journal_mode=WAL")
            self._conn.execute("PRAGMA synchronous=NORMAL")
            self._conn.execute("PRAGMA foreign_keys=ON")
            self._conn.execute("PRAGMA busy_timeout=5000")
            self._conn.execute(
                "CREATE TABLE IF NOT EXISTS schema_versions (namespace TEXT PRIMARY KEY, "
                "version INTEGER NOT NULL, applied_at REAL NOT NULL)")
        self.ensure_schema("core", CORE_MIGRATIONS)

    # -- migrations --------------------------------------------------------
    def schema_version(self, namespace: str) -> int:
        row = self.query_one("SELECT version FROM schema_versions WHERE namespace=?", (namespace,))
        return int(row["version"]) if row else 0

    def ensure_schema(self, namespace: str, migrations: Sequence[Migration]) -> int:
        """Apply migrations of ``namespace`` newer than the stored version.

        Each migration is ``(version, sql_script | callable(conn))`` and runs in
        its own transaction; versions must increase. Returns the new version.
        """
        with self._lock:
            current = self.schema_version(namespace)
            for version, step in sorted(migrations, key=lambda m: m[0]):
                if version <= current:
                    continue
                self._conn.execute("BEGIN IMMEDIATE")
                try:
                    if callable(step):
                        step(self._conn)
                    else:
                        for statement in _split_sql(step):
                            self._conn.execute(statement)
                    self._conn.execute(
                        "INSERT INTO schema_versions(namespace, version, applied_at) VALUES (?,?,?) "
                        "ON CONFLICT(namespace) DO UPDATE SET version=excluded.version, applied_at=excluded.applied_at",
                        (namespace, version, time.time()))
                    self._conn.execute("COMMIT")
                except Exception:
                    self._conn.execute("ROLLBACK")
                    raise
                current = version
            return current

    # -- basic access ------------------------------------------------------
    def execute(self, sql: str, params: Sequence[Any] | dict[str, Any] = ()) -> sqlite3.Cursor:
        with self._lock:
            return self._conn.execute(sql, params)

    def executemany(self, sql: str, seq: Iterable[Sequence[Any]]) -> None:
        with self._lock, self.transaction():
            self._conn.executemany(sql, seq)

    def query(self, sql: str, params: Sequence[Any] | dict[str, Any] = ()) -> list[dict[str, Any]]:
        with self._lock:
            return [dict(r) for r in self._conn.execute(sql, params).fetchall()]

    def query_one(self, sql: str, params: Sequence[Any] | dict[str, Any] = ()) -> dict[str, Any] | None:
        with self._lock:
            row = self._conn.execute(sql, params).fetchone()
            return dict(row) if row is not None else None

    def scalar(self, sql: str, params: Sequence[Any] | dict[str, Any] = ()) -> Any:
        with self._lock:
            row = self._conn.execute(sql, params).fetchone()
            return row[0] if row is not None else None

    def insert(self, table: str, row: dict[str, Any], *, or_ignore: bool = False) -> int:
        """Insert a dict (dict/list values are stored as JSON); return rowid."""
        if not table.replace("_", "").isalnum():
            raise ValueError("bad table name")
        cols = list(row)
        values = [(_json(v) if isinstance(v, (dict, list)) else v) for v in row.values()]
        verb = "INSERT OR IGNORE" if or_ignore else "INSERT"
        sql = f"{verb} INTO {table} ({', '.join(cols)}) VALUES ({', '.join('?' for _ in cols)})"
        with self._lock:
            return int(self._conn.execute(sql, values).lastrowid or 0)

    @contextmanager
    def transaction(self) -> Iterator[sqlite3.Connection]:
        """Explicit write transaction (re-entrant within one thread)."""
        with self._lock:
            if self._conn.in_transaction:
                yield self._conn
                return
            self._conn.execute("BEGIN IMMEDIATE")
            try:
                yield self._conn
                self._conn.execute("COMMIT")
            except BaseException:
                self._conn.execute("ROLLBACK")
                raise

    async def run(self, fn: Callable[..., Any], *args: Any) -> Any:
        """Run a heavier ``fn(db, *args)`` in a worker thread."""
        return await asyncio.to_thread(fn, self, *args)

    def close(self) -> None:
        with self._lock:
            try:
                self._conn.close()
            except sqlite3.Error:
                pass

    # -- shared helpers ------------------------------------------------------
    def log_activity(self, kind: str, name: str = "", *, ok: bool | None = None, summary: str = "",
                     detail: Any = None, duration_ms: float | None = None, source: str = "") -> int:
        """Append to the activity log. Callers must pass redacted text."""
        return self.insert("activity", {
            "at": time.time(), "kind": kind, "name": name, "ok": None if ok is None else int(ok),
            "summary": summary[:2000], "detail": None if detail is None else _json(detail)[:8000],
            "duration_ms": duration_ms, "source": source,
        })

    @staticmethod
    def quota_day(provider: str, at: float | None = None) -> str:
        """Day key for per-day counters. Gemini free quotas reset at midnight
        Pacific time; everything else is counted by the local (Iraq) day."""
        from zoneinfo import ZoneInfo
        zone = "America/Los_Angeles" if provider == "gemini" else "Asia/Baghdad"
        moment = _dt.datetime.fromtimestamp(at if at is not None else time.time(), ZoneInfo(zone))
        return moment.strftime("%Y-%m-%d")

    def bump_usage(self, provider: str, model: str, kind: str = "text", *, requests: int = 1, errors: int = 0,
                   rate_limited: int = 0, tokens_in: int = 0, tokens_out: int = 0, units: float = 0.0,
                   day: str | None = None) -> None:
        day = day or self.quota_day(provider)
        self.execute(
            "INSERT INTO usage_counters(day, provider, model, kind, requests, errors, rate_limited, tokens_in, "
            "tokens_out, units) VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT(day, provider, model, kind) DO UPDATE SET "
            "requests=requests+excluded.requests, errors=errors+excluded.errors, "
            "rate_limited=rate_limited+excluded.rate_limited, tokens_in=tokens_in+excluded.tokens_in, "
            "tokens_out=tokens_out+excluded.tokens_out, units=units+excluded.units",
            (day, provider, model, kind, requests, errors, rate_limited, tokens_in, tokens_out, units))

    def usage_for(self, provider: str, model: str, kind: str | None = None, day: str | None = None) -> dict[str, Any]:
        """Today's counters for provider/model (summed over kinds unless given)."""
        day = day or self.quota_day(provider)
        sql = ("SELECT COALESCE(SUM(requests),0) AS requests, COALESCE(SUM(errors),0) AS errors, "
               "COALESCE(SUM(rate_limited),0) AS rate_limited, COALESCE(SUM(tokens_in),0) AS tokens_in, "
               "COALESCE(SUM(tokens_out),0) AS tokens_out, COALESCE(SUM(units),0) AS units "
               "FROM usage_counters WHERE day=? AND provider=? AND model=?")
        params: list[Any] = [day, provider, model]
        if kind:
            sql += " AND kind=?"
            params.append(kind)
        return self.query_one(sql, params) or {}


def _split_sql(script: str) -> list[str]:
    """Split a migration script into statements (trigger bodies kept whole).

    ``sqlite3.complete_statement`` understands comments, string literals and
    BEGIN...END trigger bodies, so line accumulation is enough.
    """
    statements: list[str] = []
    buffer = ""
    for line in script.splitlines(keepends=True):
        buffer += line
        if sqlite3.complete_statement(buffer):
            if buffer.strip():
                statements.append(buffer.strip())
            buffer = ""
    if buffer.strip():
        statements.append(buffer.strip())
    return statements


__all__ = ["Database", "CORE_MIGRATIONS", "fts_match_expr"]
